### PR TITLE
Fix memory leak in waitDevice

### PR DESCRIPTION
**Pull request by Raffone17**
## 📑 Description

Closes # 

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [X] All the tests have passed

### CODE REVIEW

**Comment by Raffone17** [comment]
@gmacario waiting for your review!

**Comment by gmacario** [comment]
Thanks @Raffone17 for your contribution.
I am not an expert on Node.js but I believe this PR could be beneficial and proposed upstream to https://github.com/chrvadala/node-ble.

Have you already had a chance of discussing it with @chrvadala?

**Comment by gmacario** [comment]
> Have you already had a chance of discussing it with @chrvadala?

Ping @Raffone17

**Comment by gmacario** [comment]
@Raffone17 as agreed during today meeting with @chrvadala please submit the Pull Request upstream to https://github.com/chrvadala/node-ble

**Pull request closed without merging**
